import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from 'react-hot-toast';
import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ModeToggle } from "@/components/ModeToggle";

const sofiaSans = Manrope({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal 
}: Readonly<{
  children: React.ReactNode;
  authModal : React.ReactNode,
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body
        className={`${sofiaSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ThemeProvider 
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <ReactQueryProvider>

          
          <SessionProvider>
          <div className="fixed inset-0 -z-10 h-full w-full bg-background bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>
          
          
            <Navbar />
            {authModal}
            {children}
            <Toaster />

            <div className="fixed bottom-4 left-5">
              <ModeToggle />
            </div>
          </SessionProvider>
         
        </ReactQueryProvider>

        
        </ThemeProvider>
      </body>

      
    </html>
  );
}
